spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: pawan
    password: pawan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: IDENTITY-SERVICE
server:
  port: 8086
eureka:
  instance:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
